export const APP_ROUTES = {
  private: {
    goodsReturnSuccess: "/conta/devolucao-de-mercadoria/sucesso",
    goodsReturn: "/conta/devolucao-de-mercadoria",
    account: "/conta",
    confirmation: "/compra/confirmacao/[code]",
    payment: "/compra/pagamento",
    verify: "/compra/verificar",
    cart: "/compra/carrinho",
    creditAnalysisSuccess: "/credito/analise/sucesso",
    creditAnalysis: "/credito/analise",
  },
  public: {
    product: "/produto/[id]",
    register: "/registrar",
    recovery: "/recuperar",
    search: "/busca",
    login: "/entrar",
    home: "/",
    withdrawOrder: "/institucional/retire-seu-pedido-em-nossas-lojas",
    privacyPolicies: "/institucional/politica-de-privacidade",
    trabalheConosco: "/institucional/trabalhe-conosco",
    representants: "/institucional/representantes",
    contactUs: "/institucional/fale-conosco",
    howToBuy: "/institucional/como-comprar",
    televendas: "/institucional/televendas",
    aboutUs: "/institucional/sobre-nos",
  },
};
